logging:
  level:
    ROOT: info
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/cade_van
    username: postgres
    password: root
  jpa:
    database: postgresql
    show-sql: false
server:
  port: 8080
  protocol: http
