spring:
  profiles:
    active: dev
  application:
    name: Cadê a Van
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changeLog.master.yml
server:
  port: 8080
  protocol: https
